### PR TITLE
Add a command to get a JSON view of a connection

### PR DESCRIPTION
**Pull request by gulopine**

### CODE REVIEW

**Comment by lambacck** [comment]
should this be called json or connection info? Are we going to want to do something similar with a mapping?

**Comment by lambacck** [comment]
To be clear, my concern is that json is a very generic and not descriptive of what the command does.

**Comment by gulopine** [comment]
We already have the equivalent for a mapping. It used to be called `heroku connect:mapping` and now it's called `heroku connect:mapping:json`. It seems descriptive enough to me, but you're right that it's really generic. I'm open to alternatives if you have any. I'm all out. :(

**Comment by sibson** [comment]
json->details ?

**Comment by gulopine** [comment]
I'd worry about something like `details`, because we already have `info`, which is a plain-text summary of the connection and its mappings. Ideally, I'd still want to include `json` in the command in some way, to indicate what will actually be returned.

**Comment by gulopine** [comment]
I suppose another alternative is to call it `get` or `retrieve`. We'll likely have an `update`, and we already have a `create` and `delete` for mappings, and we'll presumably end up with an `update` there as well. I like the idea of them all using JSON as pass-throughs to the raw API, but that can get tricky for things like `mapping:create`, which already accept individual parameters and would have to be updated to also accept JSON. Certainly doable, though.

**Comment by sibson** [comment]
-0.5 on sending JSON to commands.  I feel like if you want to do that you should be using import.  get and retrieve sound okish.

**Comment by gulopine** [comment]
If we don't have parity JSON-wise, I'd rather not try to have parity command-name-wise. That would just get confusing. Maybe the easiest solution is to just drop the JSON commands altogether until we determine whether any users actually want them.

**Comment by sibson** [comment]
its certainly easier to give than take away :)  Having a parseable output from commands is quite useful when scripting but usually less necessary on the “calling” side.

**Comment by gulopine** [comment]
Alright then, I'm going to close this PR and open a new one to get rid of the mapping:json endpoint as well.

**Pull request closed without merging**
