### PR TITLE
Remove connect:preauth as the flow no longer needs it

### PR DESCRIPTION
**Pull request by gulopine**

### CODE REVIEW

**Comment by gulopine** [comment]
Connects to heroku/herokuconnect#2612

**Comment by gulopine** [comment]
Connects to heroku/herokuconnect#2612

**Comment by sibson** [comment]
:+1:, Does flow no longer needs it mean we're dropping support for preauth or there is a better alternative?

**Comment by gulopine** [comment]
My intention here is that the CLI flow doesn't need preauth. It's just as easy to authorize Salesforce after the connection exists (I'd actually argue it's easier because you don't need to keep track of the preauth token). The only time I see preauth being useful is when scripting a bunch of connection provisions against a single org, and I don't feel like that's a good use case for the CLI.

**Comment by sibson** [comment]
:+1:

**Pull request merged**
