### PR TITLE
Release version 0.6.0

### PR DESCRIPTION
**Pull request by codingjoe**
Changelog:
```
* Rename restart to recover (#89)
* Add environment and domain flag for sf:auth command (#87)
* Remove --login flag from sf:auth command (#85)
```

### CODE REVIEW

**Comment by codingjoe** [comment]
@sigmavirus24 I guess it would be cool to release that. So I took the liberty to open a PR ans wrote a changelog, for your convenience 👍

**Comment by sigmavirus24** [comment]
Closing and reopening to trigger a CI build (maybe)

**Comment by codingjoe** [comment]
true, github is not really reliable the past few days :/

**Comment by codingjoe** [comment]
I added a note about #89

**Comment by codingjoe** [comment]
Ping @sigmavirus24 any chance the latest commits get released?

**Comment by codingjoe** [comment]
thx 👍

**Comment by sigmavirus24** [comment]
Should be up on NPM too.

**Pull request merged**
