### PR TITLE
Remove ADDON and its console.log

### PR DESCRIPTION
**Pull request by gulopine**

### CODE REVIEW

**Comment by alouie-sfdc** [comment]
+1

**Comment by alouie-sfdc** [comment]
One suggestion: should we include a comment somewhere to warn people about console output during plugin installation?

**Comment by gulopine** [comment]
I think I'd rather raise that to the Tools team and see if we can get some better reporting out of the Toolbelt itself.

**Comment by alouie-sfdc** [comment]
Sounds good, thanks.

**Pull request merged**
